#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
xmodmap "/home/immbkhtiar/.Xmodmap"

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &
#
# Debian-local change:
#   - fbautostart has been added with a quick hack to check to see if it
#     exists. If it does, we'll start it up by default.
which fbautostart > /dev/null
if [ $? -eq 0 ]; then
    fbautostart
fi

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

exec xfsettingsd &
exec picom &
exec thunar --daemon &
exec dunst & 
# exec /usr/libexec/gvfs-udisks2-volume-monitor &
# exec /usr/libexec/gvfs-mtp-volume-monitor &
# exec /usr/libexec/gvfs-goa-volume-monitor &
# exec /usr/libexec/gvfs-gphoto2-volume-monitor &
# exec /usr/libexec/gvfs-afc-volume-monitor &
# exec /usr/libexec/gvfsd-metadata &
# exec /usr/libexec/gvfsd-trash &
# fbsetbg -f $HOME/[BAKHTIAR]/Photos/wallpaper/wallpaper11.png
exec fluxbox

# or if you want to keep a log:
# exec fluxbox -log "/home/immbkhtiar/.fluxbox/log"
