[main]
font=GeistMono Nerd Font:style=Regular:size=10
font-bold=GeistMono Nerd Font:style=Bold:size=10

# window size (approx)
initial-window-size-chars=100x30

# border padding
pad=6x6

# cursor
# cursor-color=ffffff
# cursor-blink=yes

# scrollback behaviour
# scrollback-lines=10000

[colors]

foreground=ffffff
background=212121

regular0=212121
regular1=A00000
regular2=00A000
regular3=A0A000
regular4=0000A0
regular5=A000A0
regular6=00A0A0
regular7=C0C0C0

bright0=7f7f7f
bright1=FF0000
bright2=00FF00
bright3=FFFF00
bright4=5C5CFF
bright5=FF00FF
bright6=00FFFF
bright7=ffffff

[mouse]
hide-when-typing=yes

[scrollback]
indicator-position=none

[key-bindings]

# Equivalent to Ctrl+Shift+F4 translation
# Ctrl+Shift+F4=spawn-terminal

# Font scaling (similar to Ctrl + mouse wheel)
# Ctrl+equal=font-increase
# Ctrl+minus=font-decrease
# Ctrl+0=font-reset
